### ISSUE TITLE
download_bundle 1.8 response break

### ISSUE THREAD

**Issue by araujotadeu** [crowdin/crowdin-api-client-ruby#83]
We were using version 1.6 of the AI, but when updating it to 1.8, we noticed a compatibility break in the response ( from the release notes, that's expected ). But since I could not find a confirmation of how to use the new response in the docs I am asking here.

Method: `download_bundle`

**Responses**
Version 1.6 / 1.7
```
BUNDLE bundle-XXXXXXX-XXX-XXXXX-XXX-XXXXXXXXX.zip
```
Version 1.8
```
{"data"=>{"url"=>"", "expireIn"=>"2024-04-12T13:17:41+00:00"}}
```

If I understood correctly, the downloaded local file name is the export it with a prefix and the .zip extensions. Something like
```
bundle-<EXPORT_ID>.zip
```

Is that correct?

Is there another way to get the local file name?

**Comment by andrii-bodnar** [comment]
There was a potential breaking change in the 1.8.0 release for the download methods. Related discussion - https://github.com/crowdin/crowdin-api-client-ruby/issues/66 and PR - https://github.com/crowdin/crowdin-api-client-ruby/pull/69.

Please consider using the `destination` parameter to specify the download file name. In this case, the API client will download the file to the specified place instead of returning the response.

**Comment by araujotadeu** [comment]
Thanks @andrii-bodnar, but the method I am using `download_bundle` doesn't have the destination parameter.
[Source Code](https://github.com/crowdin/crowdin-api-client-ruby/blob/98430f782c28e8f0720315aa6c15e276fd5795f8/lib/crowdin-api/api_resources/bundles.rb#L75)

**Comment by araujotadeu** [comment]
@andrii-bodnar I just noticed that the bundle API was created by a former member of our company, and probably that's why the change regarding the download methods missed the bundle one. I did create a PR with a change adding the destination parameter to the `download_bundle` method to keep the bundle API updated. PR https://github.com/crowdin/crowdin-api-client-ruby/pull/85

**Comment by andrii-bodnar** [comment]
@araujotadeu thanks a lot! 🚀
